// The variable "macros_to_document" contains the names of the macros that
// documentation should be collectes automatically from the *.sci files using
// help_from_sci().

macros_to_document = [ ...
    "MorIARTyPath" ...
    "MCreateMosaicShape" ...
    "MCreateProjector" ...
    "MProjection" ...
];
